# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d62c3cfdcbe817240b9ef532e2b5deb89812007fb597401e576eb32bff543f862a8e207a1fb09a38cc799ae915fdc9496a0e6a5f75e2944aca57d2b79bc045
  secret_token: lzal9E4HLpcIokfX6eMxQhp74
  twitter_consumer_secret: Od31oo80wHJtiS7wAtoi6yESojJ5sUPX5JQyZL5dEOQ1FLAaau

test:
  secret_key_base: 197c2cad222bcd811284db8900ecefa74242052685aa7ddab9843faa9f99934e51c3eb6b8c7772b880c40caf8aef031f666f84d167023bda5dc607886ebc96e5
  twitter_consumer_key: lzal9E4HLpcIokfX6eMxQhp74
  twitter_consumer_secret: Od31oo80wHJtiS7wAtoi6yESojJ5sUPX5JQyZL5dEOQ1FLAaau
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
